/* ============================================================
   Job Notification Tracker — Dataset
   ============================================================
   60 realistic Indian tech jobs for freshers & early career.
   ============================================================ */

var JOB_DATA = [
    {
        id: 1,
        title: "SDE Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Data Structures", "Algorithms", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹40k/month Internship",
        applyUrl: "https://www.amazon.jobs/en/jobs/sde-intern-bangalore",
        description: "Join Amazon's engineering team as an SDE Intern in Bangalore. You'll work on building scalable distributed systems that impact millions of customers. Candidates should have a strong grasp of data structures, algorithms, and object-oriented design.\n\nThis is a 6-month internship with the possibility of a full-time offer based on performance. You'll be paired with a senior mentor and contribute to production services from day one."
    },
    {
        id: 2,
        title: "Graduate Engineer Trainee",
        company: "Infosys",
        location: "Mysuru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Agile", "Communication"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "3.6–4.5 LPA",
        applyUrl: "https://www.naukri.com/job-listings-infosys-get",
        description: "Infosys is hiring Graduate Engineer Trainees for their Mysuru campus. Selected candidates will undergo a rigorous training program at Infosys Global Education Centre before being assigned to live projects.\n\nIdeal for 2024/2025 graduates with a background in CS, IT, or related engineering disciplines. Strong communication skills and a willingness to relocate are essential."
    },
    {
        id: 3,
        title: "Frontend Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["React", "JavaScript", "HTML", "CSS", "Git"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹35k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/flipkart-frontend-intern",
        description: "Flipkart's commerce platform team is looking for a Frontend Intern to help build next-generation shopping experiences. You'll work with React, collaborate with designers, and ship features used by millions of Indian consumers.\n\nThis is a hands-on role — expect to write production code within your first two weeks. Strong fundamentals in JavaScript and an eye for UI detail are required."
    },
    {
        id: 4,
        title: "Java Developer (0-1 years)",
        company: "TCS",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "MySQL", "REST APIs"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "3.5–5 LPA",
        applyUrl: "https://www.naukri.com/job-listings-tcs-java-developer",
        description: "TCS Digital is hiring Java Developers for their Chennai delivery centre. You'll work on enterprise-grade banking and insurance applications using Spring Boot and microservices architecture.\n\nCandidates with 0-1 years of experience and strong Java fundamentals are preferred. Knowledge of REST APIs and relational databases is a plus."
    },
    {
        id: 5,
        title: "Python Developer (Fresher)",
        company: "Wipro",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Django", "PostgreSQL", "Linux"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "3–4.5 LPA",
        applyUrl: "https://www.indeed.co.in/viewjob/wipro-python-developer",
        description: "Wipro WILP program is hiring Python Developers for their Hyderabad campus. You'll be part of a team building internal automation tools and data processing pipelines.\n\nFreshers with strong Python skills and familiarity with Django or Flask are encouraged to apply. Training will be provided on enterprise tools and workflows."
    },
    {
        id: 6,
        title: "React Developer (1-3 years)",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "TypeScript", "Redux", "Node.js", "Jest"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/razorpay-react-developer",
        description: "Razorpay's Dashboard team is looking for a React Developer to build merchant-facing payment tools. You'll own complete features end-to-end — from API integration to pixel-perfect UI implementation.\n\nWe value clean code, thoughtful component design, and a bias for shipping. Experience with TypeScript and state management libraries is strongly preferred."
    },
    {
        id: 7,
        title: "QA Intern",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "Java", "Test Cases"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "₹20k/month Internship",
        applyUrl: "https://www.naukri.com/job-listings-zoho-qa-intern",
        description: "Zoho is hiring QA Interns for their Chennai office. You'll work alongside the Zoho CRM team to write and execute test cases, automate regression suites, and ensure product quality.\n\nStrong analytical thinking and attention to detail are essential. Familiarity with Selenium WebDriver and basic Java is preferred."
    },
    {
        id: 8,
        title: "Data Analyst Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["SQL", "Excel", "Python", "Tableau", "Statistics"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/swiggy-data-analyst-intern",
        description: "Swiggy's Business Intelligence team is looking for a Data Analyst Intern. You'll analyze delivery patterns, merchant performance, and customer behavior to generate actionable insights.\n\nProficiency in SQL is mandatory. Experience with Python for data manipulation and a basic understanding of statistical methods will set you apart."
    },
    {
        id: 9,
        title: "Junior Backend Developer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Kafka", "MongoDB", "Docker"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "8–12 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/phonepe-junior-backend",
        description: "PhonePe is hiring Junior Backend Developers to work on India's largest UPI payments platform. You'll build high-throughput APIs handling millions of transactions per second.\n\nIdeal candidates have strong Java fundamentals and exposure to distributed systems concepts. Experience with message queues and containerization is a bonus."
    },
    {
        id: 10,
        title: "SDE Intern",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Kotlin", "Android", "REST APIs", "Git"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹40k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/cred-sde-intern",
        description: "CRED is looking for SDE Interns to join their mobile engineering team. You'll work on building premium fintech experiences for Android using Kotlin and modern architecture patterns.\n\nWe're looking for builders who care deeply about craft. Strong problem-solving skills and familiarity with mobile development lifecycles are expected."
    },
    {
        id: 11,
        title: "Graduate Engineer Trainee",
        company: "Cognizant",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", ".NET", "SQL", "Agile"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "3–4 LPA",
        applyUrl: "https://www.naukri.com/job-listings-cognizant-get-pune",
        description: "Cognizant GenC program is hiring Graduate Engineer Trainees for their Pune location. You'll undergo structured training before being placed on client-facing technology projects.\n\nOpen to 2024/2025 graduates from CS, IT, ECE, and EEE branches. Minimum 60% throughout academics is required."
    },
    {
        id: 12,
        title: "Frontend Developer (1-3 years)",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "JavaScript", "CSS", "Webpack", "REST APIs"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "8–14 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/freshworks-frontend-dev",
        description: "Freshworks is hiring Frontend Developers to build world-class SaaS products used by 60,000+ businesses globally. You'll work on Freshdesk's agent experience using React and modern CSS.\n\nWe need engineers who obsess over performance, accessibility, and component reusability. Experience with design systems is a strong plus."
    },
    {
        id: 13,
        title: "Python Developer (Fresher)",
        company: "Accenture",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Flask", "SQL", "Linux", "Git"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "3.5–5 LPA",
        applyUrl: "https://www.indeed.co.in/viewjob/accenture-python-fresher",
        description: "Accenture India is hiring Python Developers for their Mumbai Advanced Technology Centre. You'll work on automation frameworks, data processing scripts, and internal tooling.\n\nFreshers with a solid foundation in Python programming and Linux environments are welcome. Certification in Python or cloud platforms is a plus."
    },
    {
        id: 14,
        title: "Data Analyst Intern",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["SQL", "Python", "Excel", "Power BI"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "₹25k/month Internship",
        applyUrl: "https://www.naukri.com/job-listings-paytm-data-analyst-intern",
        description: "Paytm's fintech analytics team is looking for Data Analyst Interns at their Noida headquarters. You'll work with transaction data, fraud patterns, and merchant insights.\n\nStrong SQL skills are a must. Exposure to Power BI or Tableau for visualization and basic Python for data wrangling are expected."
    },
    {
        id: 15,
        title: "Java Developer (0-1 years)",
        company: "Capgemini",
        location: "Pune",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Spring", "Hibernate", "MySQL", "Maven"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.naukri.com/job-listings-capgemini-java-pune",
        description: "Capgemini is hiring Java Developers for their Pune delivery centre. You'll work on large-scale enterprise applications for banking and insurance clients across Europe and the US.\n\nCandidates should have solid Java and Spring Framework experience. Familiarity with CI/CD pipelines and Agile methodologies is preferred."
    },
    {
        id: 16,
        title: "SDE Intern",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Haskell", "PureScript", "Functional Programming", "Git"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹35k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/juspay-sde-intern",
        description: "Juspay is hiring SDE Interns to work on India's payment orchestration infrastructure. You'll use functional programming languages to build highly reliable, type-safe payment systems.\n\nThis role is ideal for engineers passionate about correctness and elegance. Exposure to Haskell or any typed functional language is a strong advantage."
    },
    {
        id: 17,
        title: "React Developer (1-3 years)",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "Next.js", "TypeScript", "GraphQL", "CSS-in-JS"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "12–18 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/flipkart-react-developer",
        description: "Flipkart's web platform team needs a React Developer to build fast, accessible shopping experiences for India's largest e-commerce platform. You'll work on server-rendered pages, progressive web app features, and design system components.\n\nExperience with Next.js and performance optimization is highly valued. You should be comfortable with both pixel-perfect UI and complex state management."
    },
    {
        id: 18,
        title: "Junior Backend Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "REST APIs", "MySQL", "Linux"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "6–10 LPA",
        applyUrl: "https://www.naukri.com/job-listings-zoho-backend-dev",
        description: "Zoho is hiring Junior Backend Developers for their core products division in Chennai. You'll build APIs and services that power Zoho's suite of 50+ business applications used worldwide.\n\nZoho values deep engineering fundamentals over framework knowledge. Be prepared for a rigorous technical interview focused on problem-solving and system design basics."
    },
    {
        id: 19,
        title: "QA Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Selenium", "Java", "API Testing", "JIRA"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/flipkart-qa-intern",
        description: "Join Flipkart's quality assurance team as a QA Intern. You'll test checkout flows, payment integrations, and logistics features across web and mobile platforms.\n\nYou should be comfortable writing test automation scripts and have a methodical approach to uncovering edge cases. Experience with JIRA and CI pipelines is a bonus."
    },
    {
        id: 20,
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C", "Java", "DBMS", "Networking", "Communication"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "3.3–3.6 LPA",
        applyUrl: "https://www.naukri.com/job-listings-tcs-ninja-get",
        description: "TCS Ninja hiring is open for 2025 graduates. Selected candidates will be onboarded through TCS iON digital learning platform and placed across various technology practices in Mumbai.\n\nThis role is ideal for freshers looking for stable career growth in a global IT services company. All engineering branches are eligible with minimum 60% aggregate."
    },
    {
        id: 21,
        title: "Frontend Intern",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "TypeScript", "CSS", "Figma", "Git"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹40k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/cred-frontend-intern",
        description: "CRED is looking for Frontend Interns who care about premium user experiences. You'll translate Figma designs into flawless React components for CRED's web platform.\n\nWe're looking for candidates with a strong aesthetic sense and clean coding habits. Experience with CSS animations and TypeScript is preferred."
    },
    {
        id: 22,
        title: "Python Developer (Fresher)",
        company: "IBM",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "AWS"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "4.5–6 LPA",
        applyUrl: "https://www.indeed.co.in/viewjob/ibm-python-developer",
        description: "IBM India is hiring Python Developers for their Cloud & AI division in Bangalore. You'll build microservices, API integrations, and automation tools for IBM Cloud platform.\n\nFreshers with strong Python skills and exposure to cloud-native development using Docker and AWS are ideal. IBM provides excellent learning pathways and certifications."
    },
    {
        id: 23,
        title: "Java Developer (0-1 years)",
        company: "Oracle",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Oracle DB", "PL/SQL", "Spring Boot", "JUnit"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "6–10 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/oracle-java-developer-hyd",
        description: "Oracle's Cloud Infrastructure team in Hyderabad is looking for Java Developers. You'll work on building next-gen database management tools and cloud services.\n\nStrong fundamentals in Java, SQL, and automated testing are expected. Oracle offers competitive compensation and the chance to work on products used by Fortune 500 companies."
    },
    {
        id: 24,
        title: "SDE Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Go", "Python", "REST APIs", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹40k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/razorpay-sde-intern",
        description: "Razorpay is looking for SDE Interns to build payment infrastructure that powers India's digital economy. You'll work with Go and Python on high-performance services processing millions of transactions.\n\nWe need engineers who think in systems, not just features. Strong DSA fundamentals and a working knowledge of at least one backend language are expected."
    },
    {
        id: 25,
        title: "React Developer (1-3 years)",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "JavaScript", "Redux", "Node.js", "Webpack"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "10–15 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/swiggy-react-developer",
        description: "Swiggy's consumer web team is hiring React Developers to build fast, delightful food ordering experiences. You'll optimize for Core Web Vitals, implement lazy loading strategies, and build reusable component libraries.\n\nExperience with performance profiling, A/B testing frameworks, and server-side rendering is valued. We move fast and ship daily."
    },
    {
        id: 26,
        title: "Data Analyst Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["SQL", "Python", "Pandas", "Looker", "Statistics"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹35k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/razorpay-data-analyst-intern",
        description: "Razorpay's data team is looking for a Data Analyst Intern to help measure product adoption, payment success rates, and merchant growth. You'll build dashboards and present insights to product leaders.\n\nStrong SQL and analytical thinking are mandatory. Experience with Python for data analysis and visualization tools like Looker or Metabase is a plus."
    },
    {
        id: 27,
        title: "Junior Backend Developer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Ruby", "Rails", "PostgreSQL", "Redis", "Git"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "6–10 LPA",
        applyUrl: "https://www.naukri.com/job-listings-freshworks-backend",
        description: "Freshworks is hiring Junior Backend Developers for their messaging products team. You'll build scalable APIs and real-time features using Ruby on Rails and Redis.\n\nWe value engineers who write clean, well-tested code and communicate effectively. Prior experience with background job processing and caching strategies is a bonus."
    },
    {
        id: 28,
        title: "Graduate Engineer Trainee",
        company: "Wipro",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Python", "SQL", "Soft Skills"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "3.5–4 LPA",
        applyUrl: "https://www.naukri.com/job-listings-wipro-get-bangalore",
        description: "Wipro Elite National Talent Hunt is hiring Graduate Engineer Trainees across multiple locations. Selected candidates undergo an intensive training at Wipro campuses before project allocation.\n\nAll engineering branches are eligible. Candidates must clear Wipro's aptitude test and technical round. Strong problem-solving skills are essential."
    },
    {
        id: 29,
        title: "Frontend Developer (1-3 years)",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "JavaScript", "CSS", "Webpack", "Jest"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "8–14 LPA",
        applyUrl: "https://www.naukri.com/job-listings-paytm-frontend-dev",
        description: "Paytm is hiring Frontend Developers to build payment and commerce experiences for 300M+ users. You'll work on the Paytm web app, merchant dashboard, and internal tools.\n\nExperience with React, responsive design, and cross-browser compatibility is essential. We value engineers who can balance speed with quality."
    },
    {
        id: 30,
        title: "QA Intern",
        company: "Accenture",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "Python", "Test Planning"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "₹15k/month Internship",
        applyUrl: "https://www.indeed.co.in/viewjob/accenture-qa-intern-pune",
        description: "Accenture's Testing Centre of Excellence is hiring QA Interns for their Pune campus. You'll learn industry-standard testing methodologies and contribute to quality assurance for global enterprise clients.\n\nGreat opportunity for freshers to build a career in quality engineering. Training on automation tools and frameworks will be provided."
    },
    {
        id: 31,
        title: "SDE Intern",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Kotlin", "Android", "Firebase"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹35k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/phonepe-sde-intern",
        description: "PhonePe is hiring SDE Interns for their Android team. You'll work on features that serve 400M+ registered users making daily payments, investments, and insurance purchases.\n\nStrong fundamentals in Java or Kotlin and experience building Android apps (even personal projects) are required. Performance-conscious engineers are preferred."
    },
    {
        id: 32,
        title: "Python Developer (Fresher)",
        company: "SAP",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "Django", "REST APIs", "SAP HANA", "Git"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "5–7 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/sap-python-developer",
        description: "SAP Labs India is hiring Python Developers for their Enterprise Cloud team. You'll build integration services and developer tools for SAP's business applications platform.\n\nFreshers with strong Python skills and an interest in enterprise software are welcome. SAP provides structured onboarding and global exposure from day one."
    },
    {
        id: 33,
        title: "Java Developer (0-1 years)",
        company: "Dell",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Microservices", "Jenkins", "Git"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "5–8 LPA",
        applyUrl: "https://www.indeed.co.in/viewjob/dell-java-developer-hyd",
        description: "Dell Technologies is hiring Java Developers for their Server Solutions team in Hyderabad. You'll work on enterprise infrastructure management tools used by data centres worldwide.\n\nCandidates should have a solid understanding of Java, Spring Boot, and microservices patterns. Experience with CI/CD tools like Jenkins is a plus."
    },
    {
        id: 34,
        title: "Frontend Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "TypeScript", "Tailwind CSS", "Storybook"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹35k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/razorpay-frontend-intern",
        description: "Razorpay is looking for Frontend Interns to build merchant-facing payment dashboards. You'll work with React, TypeScript, and a custom design system to ship polished, production-quality interfaces.\n\nWe need interns who think like engineers, not just coders. Attention to accessibility, loading states, and error handling is expected."
    },
    {
        id: 35,
        title: "React Developer (1-3 years)",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "PureScript", "Functional JS", "CSS", "Git"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "10–16 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/juspay-react-developer",
        description: "Juspay is hiring React Developers to build payment checkout experiences used by major banks and e-commerce platforms. You'll work with functional programming principles applied to UI development.\n\nExperience with React Hooks, composable component patterns, and performance optimization is required. Exposure to PureScript or Elm is a strong differentiator."
    },
    {
        id: 36,
        title: "Graduate Engineer Trainee",
        company: "Accenture",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Cloud", "Agile", "Problem Solving"],
        source: "Naukri",
        postedDaysAgo: 10,
        salaryRange: "4–5 LPA",
        applyUrl: "https://www.naukri.com/job-listings-accenture-get",
        description: "Accenture's Advanced Technology team is hiring GETs for their Bangalore campus. You'll work on cutting-edge projects in cloud migration, AI, and digital transformation for Fortune 500 clients.\n\nNewer hires get access to Accenture's global learning platform with 24,000+ courses. Minimum 65% in graduation is required."
    },
    {
        id: 37,
        title: "Junior Backend Developer",
        company: "Amazon",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "AWS", "DynamoDB", "Lambda", "Microservices"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–18 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/amazon-jr-backend-hyd",
        description: "Amazon India's retail platform team in Hyderabad is hiring Junior Backend Developers. You'll build services that power catalog management, pricing, and inventory systems for amazon.in.\n\nStrong data structures knowledge and experience with AWS services are expected. Amazon uses a bar raiser interview process — prepare for system design and behavioral rounds."
    },
    {
        id: 38,
        title: "Data Analyst Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["SQL", "Python", "Hive", "Tableau", "Statistics"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/flipkart-data-analyst-intern",
        description: "Flipkart's supply chain analytics team needs a Data Analyst Intern to optimize warehouse operations, delivery routes, and inventory placement across India.\n\nStrong SQL skills and statistical thinking are essential. Experience with big data tools like Hive or Spark is a significant advantage."
    },
    {
        id: 39,
        title: "Frontend Developer (1-3 years)",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "JavaScript", "CSS", "Performance Optimization"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "10–16 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/phonepe-frontend-dev",
        description: "PhonePe is hiring Frontend Developers to build India's most used digital payment interface. You'll work on optimizing page load times for low-bandwidth networks and building accessible UI components.\n\nExperience with React, responsive design, and web performance tools like Lighthouse is required. Thrive in a fast-paced environment that ships weekly."
    },
    {
        id: 40,
        title: "Python Developer (Fresher)",
        company: "Cognizant",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Flask", "SQL", "AWS Lambda"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "3.5–5 LPA",
        applyUrl: "https://www.naukri.com/job-listings-cognizant-python-dev",
        description: "Cognizant's Digital Engineering practice is hiring Python Developers for their Chennai centre. You'll build serverless applications, automation scripts, and data pipelines for global healthcare clients.\n\nFreshers with solid Python fundamentals and basic AWS knowledge are encouraged to apply. Training on advanced cloud services will be provided."
    },
    {
        id: 41,
        title: "SDE Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Data Structures", "System Design", "Git"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹40k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/flipkart-sde-intern-2025",
        description: "Flipkart is hiring SDE Interns for their 2025 summer cohort. You'll work on distributed systems powering India's largest e-commerce marketplace, tackling challenges of scale, reliability, and speed.\n\nExpect a rigorous coding interview followed by a system design discussion. Top performers receive pre-placement offers."
    },
    {
        id: 42,
        title: "QA Intern",
        company: "Cognizant",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Manual Testing", "JIRA", "SQL", "Agile"],
        source: "Indeed",
        postedDaysAgo: 8,
        salaryRange: "₹15k/month Internship",
        applyUrl: "https://www.indeed.co.in/viewjob/cognizant-qa-intern",
        description: "Cognizant's Quality Engineering team is hiring QA Interns in Hyderabad. You'll work alongside senior QA engineers to test enterprise applications for banking and retail clients.\n\nBasic understanding of testing concepts, SQL for database validation, and familiarity with Agile workflows is expected. A great entry point into quality assurance."
    },
    {
        id: 43,
        title: "React Developer (1-3 years)",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "JavaScript", "TypeScript", "REST APIs", "CSS"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "8–14 LPA",
        applyUrl: "https://www.naukri.com/job-listings-zoho-react-developer",
        description: "Zoho is hiring React Developers for their CRM product suite. You'll build enterprise UI components that are used by millions of businesses globally. Zoho builds everything in-house — no third-party dependencies.\n\nStrong vanilla JavaScript knowledge is essential — Zoho values understanding over framework reliance. Be prepared for a multi-round technical evaluation."
    },
    {
        id: 44,
        title: "Junior Backend Developer",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1",
        skills: ["Go", "Microservices", "Kafka", "PostgreSQL", "Docker"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–14 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/swiggy-jr-backend",
        description: "Swiggy is hiring Junior Backend Developers for their logistics platform. You'll build services that optimize delivery routing, rider assignment, and real-time order tracking for 600+ cities.\n\nExperience with Go or willingness to learn is required. Understanding of event-driven architecture and distributed systems concepts is a bonus."
    },
    {
        id: 45,
        title: "Frontend Intern",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "JavaScript", "HTML", "CSS"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "₹20k/month Internship",
        applyUrl: "https://www.naukri.com/job-listings-paytm-frontend-intern",
        description: "Paytm is looking for Frontend Interns to work on their merchant tools dashboard. You'll build forms, tables, and interactive data visualizations for Paytm's business platform.\n\nStrong HTML/CSS fundamentals and basic React knowledge are required. You'll be mentored by senior engineers and ship code to production."
    },
    {
        id: 46,
        title: "Java Developer (0-1 years)",
        company: "Infosys",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Microservices", "Oracle DB"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "3.6–5 LPA",
        applyUrl: "https://www.naukri.com/job-listings-infosys-java-dev-pune",
        description: "Infosys is hiring Java Developers for their Financial Services unit in Pune. You'll work on core banking systems and payment processing platforms for major US and EU banks.\n\nCandidates with 0-1 years experience and strong Java/Spring Boot skills are preferred. Infosys provides visa sponsorship for onsite opportunities after 18 months."
    },
    {
        id: 47,
        title: "Data Analyst Intern",
        company: "Amazon",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["SQL", "Python", "AWS QuickSight", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹35k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/amazon-data-analyst-intern",
        description: "Amazon's operations team in Hyderabad is hiring Data Analyst Interns to analyze fulfilment centre efficiency, last-mile delivery metrics, and customer experience KPIs.\n\nStrong SQL proficiency is mandatory. Familiarity with AWS analytics services and ability to present insights to non-technical stakeholders are valued."
    },
    {
        id: 48,
        title: "SDE Intern",
        company: "Infosys",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Java", "Data Structures", "Algorithms"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "₹20k/month Internship",
        applyUrl: "https://www.naukri.com/job-listings-infosys-sde-intern",
        description: "Infosys Instep program offers SDE internships for pre-final year students. You'll contribute to real projects across digital commerce, AI platforms, and cloud infrastructure.\n\nStrong coding fundamentals in Python or Java and good problem-solving abilities are essential. Top performers receive pre-placement interview opportunities."
    },
    {
        id: 49,
        title: "Frontend Developer (1-3 years)",
        company: "Amazon",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "TypeScript", "AWS Amplify", "GraphQL", "Accessibility"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–22 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/amazon-frontend-dev-blr",
        description: "Amazon's Devices team in Bangalore is hiring Frontend Developers to build customer-facing web applications for Alexa, Fire TV, and Kindle ecosystems.\n\nStrong React and TypeScript skills are essential. Experience with accessibility standards (WCAG) and serverless architectures is highly valued. Amazon leadership principles guide all hiring decisions."
    },
    {
        id: 50,
        title: "Python Developer (Fresher)",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "FastAPI", "Redis", "PostgreSQL", "Docker"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "5–7 LPA",
        applyUrl: "https://www.naukri.com/job-listings-freshworks-python-dev",
        description: "Freshworks is looking for Python Developers to build backend services for Freshservice, their IT service management product. You'll design APIs, build integrations, and optimize database queries.\n\nFreshers with a portfolio of Python projects and familiarity with FastAPI or Flask are ideal candidates. A passion for building reliable software is a must."
    },
    {
        id: 51,
        title: "Junior Backend Developer",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Kubernetes", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12–18 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/cred-junior-backend-dev",
        description: "CRED is hiring Junior Backend Developers to build financial products that reward creditworthy individuals. You'll work on payment processing, rewards engine, and merchant integrations.\n\nCRED's engineering bar is high — expect deep technical interviews covering system design, concurrency, and database optimization. Strong Java and distributed systems understanding is expected."
    },
    {
        id: 52,
        title: "React Developer (1-3 years)",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "Next.js", "JavaScript", "Tailwind CSS"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "8–14 LPA",
        applyUrl: "https://www.naukri.com/job-listings-paytm-react-developer",
        description: "Paytm is hiring React Developers for their financial services division. You'll build investment dashboards, insurance comparison tools, and wealth management interfaces for Paytm Money.\n\nExperience with Next.js, server-side rendering, and charting libraries is preferred. You should be comfortable working with complex financial data and real-time updates."
    },
    {
        id: 53,
        title: "QA Intern",
        company: "TCS",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "Python", "SQL"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "₹15k/month Internship",
        applyUrl: "https://www.naukri.com/job-listings-tcs-qa-intern",
        description: "TCS is hiring QA Interns for their Quality Engineering practice in Hyderabad. You'll test large-scale enterprise applications for telecom and retail clients, learning industry-standard QA processes.\n\nBasic knowledge of testing lifecycle, SQL for data validation, and willingness to learn automation tools is required. A structured path to full-time employment is available."
    },
    {
        id: 54,
        title: "Graduate Engineer Trainee",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Python", "SQL", "Cloud Basics"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "https://www.naukri.com/job-listings-capgemini-get-mumbai",
        description: "Capgemini is hiring Graduate Engineer Trainees for their Mumbai delivery centre. Selected candidates will be trained on specific technology stacks based on project needs and client requirements.\n\nAll engineering graduates with minimum 60% marks are eligible. Capgemini offers global exposure and fast-tracked career growth for high performers."
    },
    {
        id: 55,
        title: "SDE Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Java", "Kotlin", "Data Structures", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹35k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/swiggy-sde-intern",
        description: "Swiggy is hiring SDE Interns for their order management and payment systems teams. You'll work on backend services handling hundreds of thousands of concurrent food orders.\n\nStrong DSA fundamentals and proficiency in Java or Kotlin are required. Expect a coding assessment followed by two technical interview rounds."
    },
    {
        id: 56,
        title: "Frontend Intern",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["JavaScript", "HTML", "CSS", "DOM APIs"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "₹20k/month Internship",
        applyUrl: "https://www.naukri.com/job-listings-zoho-frontend-intern",
        description: "Zoho is hiring Frontend Interns for their Workplace suite (Zoho Mail, Cliq, Connect). You'll work with vanilla JavaScript — no frameworks — building high-performance UI components.\n\nZoho values deep understanding of web fundamentals over framework knowledge. Strong JavaScript skills and curiosity about browser internals are essential."
    },
    {
        id: 57,
        title: "Java Developer (0-1 years)",
        company: "IBM",
        location: "Pune",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Db2", "REST APIs", "Docker"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "5–8 LPA",
        applyUrl: "https://www.indeed.co.in/viewjob/ibm-java-developer-pune",
        description: "IBM India is hiring Java Developers for their Hybrid Cloud division in Pune. You'll build middleware and integration services that connect enterprise systems across cloud and on-premise environments.\n\nStrong Java fundamentals and experience with Spring Boot are essential. IBM offers excellent technical mentorship and pathways to specialise in cloud-native development."
    },
    {
        id: 58,
        title: "Data Analyst Intern",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["SQL", "Python", "Excel", "Redash", "Statistics"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://www.linkedin.com/jobs/view/phonepe-data-analyst-intern",
        description: "PhonePe's growth analytics team is hiring Data Analyst Interns. You'll analyse user acquisition funnels, transaction patterns, and feature adoption metrics that directly influence product decisions.\n\nAdvanced SQL skills and statistical reasoning are mandatory. Experience with Python for analysis and dashboard tools like Redash or Superset is preferred."
    },
    {
        id: 59,
        title: "Junior Backend Developer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1",
        skills: ["Go", "gRPC", "PostgreSQL", "Kafka", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "12–18 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/razorpay-jr-backend",
        description: "Razorpay is hiring Junior Backend Developers for their core payments infrastructure. You'll design APIs and event-driven services handling billions of rupees in daily transaction volume.\n\nProficiency in Go (or strong willingness to learn) and understanding of distributed systems, database optimisation, and message queues is expected. This is a high-impact, high-autonomy role."
    },
    {
        id: 60,
        title: "React Developer (1-3 years)",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "TypeScript", "Framer Motion", "CSS", "Figma"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "14–22 LPA",
        applyUrl: "https://www.linkedin.com/jobs/view/cred-react-developer",
        description: "CRED is hiring React Developers to craft premium, animation-rich web experiences. You'll work closely with CRED's design team — known for raising the bar in Indian fintech UI — to build polished, performant interfaces.\n\nExperience with Framer Motion, micro-interactions, and design system contribution is highly valued. We look for engineers who have strong aesthetic judgement and clean code discipline."
    }
];
